furniture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('store/', include('store.urls')),
    path('user/', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('contact', views.contact_page, name='contact_page'),
    path('about', views.about_page, name='about_page'),
    path('reports', views.reports, name='reports')

]

store/urls.py
from django.urls import path
from store import views

urlpatterns = [
    path('add/products', views.add_product, name='add-product'),
    path('products', views.search_products, name='search-product'),
    path('carts', views.checkout, name='carts'),
    path('products/all/reports', views.ProductAllReport.as_view(), name='report-products'),
    path('customers/all/reports', views.CustomerAllReport.as_view(), name='report-customers'),
    path('update/sessions', views.update_Session, name='update-session'),

]

store/models.py
from django.db import models
from users.models import User


class Products(models.Model):
    STATUS_CHOICES = (
        (1, 'sale'),
        (2, 'new arrival'),
        (3, 'best seller'),
    )
    CATEGORY_CHOICES = (
        (1, 'Skirts'),
        (2, 'Panatlon'),
        (3, 'T-shirt'),
        (4, 'SweatShirt'),
        (5, 'pullover'),
    )
    category = models.SmallIntegerField(null=True, blank=True, choices=CATEGORY_CHOICES)
    name = models.CharField(max_length=255, null=True)
    price = models.IntegerField(null=True)
    quantity = models.IntegerField(null=True)
    image = models.ImageField(max_length=100, null=True)
    status = models.SmallIntegerField(null=True, blank=True, choices=STATUS_CHOICES)

    def __str__(self):
        return self.name


class WishList(models.Model):
    customer = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    list = models.ManyToManyField(Products, null=True, blank=True)

    def __str__(self):
        return self.customer.first_name


class Voucher(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    phone = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    products = models.ManyToManyField(Products, null=True, blank=True)
    date_checked = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

store/views.py
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from . import models, fiters
from django.template.loader import get_template
from furniture.utils import render_to_pdf
from users.models import User
from datetime import datetime
from django.http import HttpResponse
from django.views.generic import View


def add_product(request):
    if request.method == 'POST' and request.FILES:
        name = request.POST.get('name')
        image = request.FILES['image']
        price = request.POST.get('price')
        quantity = request.POST.get('quantity')
        status = request.POST.get('status')
        category = request.POST.get('category')
        fs = FileSystemStorage()
        filename = fs.save(image.name, image)
        product = models.Products(name=name, category=category, image=image, status=int(status), price=price,
                                  quantity=quantity)
        product.save()
        if product.pk:
            return redirect('search-product')
        else:
            return redirect('home_page')
    return render(request, 'store/add_product.html')


def update_Session(request):
    if request.method == "POST" and request.is_ajax:
        items = request.POST.getlist('items[]')
        request.session['items'] = items
        return HttpResponse('Success')


def search_products(request):
    products = models.Products.objects.all()
    prod_filter = fiters.ProductsFilter(request.GET, queryset=products)
    prods = prod_filter.qs
    context = {"products": prods, "myfilter": prod_filter}
    return render(request, 'store/products.html', context=context)


def checkout(request):
    items = request.session['items']
    items_obj = models.Products.objects.filter(pk__in=items)
    total = 0
    for item in items_obj:
        total = total + item.price
    context = {"items": items_obj, 'total': total}
    if request.method == 'POST' and request.is_ajax:
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        voucher = models.Voucher(name=name, address=address, phone=phone)
        voucher.save()
        voucher.products.set(items_obj)
        if voucher.pk:
            return HttpResponse('success')
        else:
            return HttpResponse('fail')
    return render(request, 'store/cart.html', context=context)


class ProductAllReport(View):
    def get(self, request, *args, **kwargs):
        template = get_template('products-all-pdf.html')
        products = models.Products.objects.all()
        user_obj = User.objects.get(pk=request.user.pk)
        context = {
            "company": "Furniture Home ",
            "user": user_obj,
            "products": products,
            "topic": "Report for All Products ",
            "today": datetime.today().strftime('%Y-%m-%d'),
        }
        html = template.render(context)
        pdf = render_to_pdf('products-all-pdf.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" % ("12341231")
            content = "inline; filename='%s'" % (filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" % (filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


class CustomerAllReport(View):
    def get(self, request, *args, **kwargs):
        template = get_template('customer-all-pdf.html')
        customers = User.objects.filter(user_type=2)
        user_obj = User.objects.get(pk=request.user.pk)
        context = {
            "company": "Furniture Home ",
            "user": user_obj,
            "customers": customers,
            "topic": "Report for All Customers ",
            "today": datetime.today().strftime('%Y-%m-%d'),
        }
        html = template.render(context)
        pdf = render_to_pdf('customer-all-pdf.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" % ("12341231")
            content = "inline; filename='%s'" % (filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" % (filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")

store/templates/store/add_product.html
{% extends 'main.html' %}

{% load static %}


{% block title %} Add Product || إضافة منتج  {% endblock title %}

{% block body %}

    <section class="hero-wrap hero-wrap-2" style="background-image: url('../../../static/images/bg_2.jpg');"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate mb-5 text-center">
                    <p class="breadcrumbs mb-0"><span class="mr-2"><a href="{% url 'home_page' %}">Home <i
                            class="fa fa-chevron-right"></i></a></span> <span>ADD Product <i
                            class="fa fa-chevron-right"></i></span></p>
                    <h2 class="mb-0 bread">ADD Product</h2>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="wrapper px-md-4">
                        <div class="row mb-5">
                            <div class="col-md-3">
                                <div class="dbox w-100 text-center">
                                    <div class="icon d-flex align-items-center justify-content-center">
                                        <span class="fa fa-map-marker"></span>
                                    </div>
                                    <div class="text">
                                        <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="dbox w-100 text-center">
                                    <div class="icon d-flex align-items-center justify-content-center">
                                        <span class="fa fa-phone"></span>
                                    </div>
                                    <div class="text">
                                        <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="dbox w-100 text-center">
                                    <div class="icon d-flex align-items-center justify-content-center">
                                        <span class="fa fa-paper-plane"></span>
                                    </div>
                                    <div class="text">
                                        <p><span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="dbox w-100 text-center">
                                    <div class="icon d-flex align-items-center justify-content-center">
                                        <span class="fa fa-globe"></span>
                                    </div>
                                    <div class="text">
                                        <p><span>Website</span> <a href="#">yoursite.com</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-md-7">
                                <div class="contact-wrap w-100 p-md-5 p-4">
                                    <h3 class="mb-4">Add Product</h3>
                                    <form method="POST" id="contactForm" enctype="multipart/form-data"
                                          name="contactForm" class="contactForm">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="label" for="name">Name</label>
                                                    <input type="text" class="form-control" name="name" id="name"
                                                           placeholder="Name">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="label" for="price">Price</label>
                                                    <input type="number" class="form-control" name="price" id="price"
                                                           placeholder="Price ">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="status">Status</label>
                                                    <select id="status" name="status" class="form-control">
                                                        <option value="1">Sale</option>
                                                        <option value="2">New Arrival</option>
                                                        <option value="3">Best Seller</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="category">Category</label>
                                                    <select id="category" name="category" class="form-control">
                                                        <option value="1">Skirts</option>
                                                        <option value="2"> Pantaloon</option>
                                                        <option value="3"> T-shirt</option>
                                                        <option value="4"> Sweatshirt</option>
                                                        <option value="5"> Pullover</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-12">
                                                <div class="input-group col-md-6 d-flex mb-3">
                                                    <label class="label" for="quantity">Quantity</label>

                                                    <span class="input-group-btn mr-2">
	                	<button type="button" class="quantity-left-minus btn" data-type="minus" data-field="">
	                   <i class="fa fa-minus"></i>
	                	</button>
	            		</span>
                                                    <input type="text" id="quantity" name="quantity"
                                                           class="quantity form-control input-number" value="1" min="1"
                                                           max="100">
                                                    <span class="input-group-btn ml-2">
	                	<button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">
	                     <i class="fa fa-plus"></i>
	                 </button>
	             	</span>
                                                </div>
                                            </div>

                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="subject">Image</label>
                                                    <input type="file" class="form-control" name="image" id="image"
                                                           placeholder="Image">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <input type="submit" value="Add" class="btn btn-primary">
                                                    <div class="submitting"></div>
                                                </div>
                                            </div>

                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-5 order-md-first d-flex align-items-stretch">
                                <div class="map">
                                    <img class="img-fluid" style="width: 29rem;height: 92vh;"
                                         src="{% static 'images/image_5.jpg' %}"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock body %}


{% block javascript %}
    <script>
        $(document).ready(function () {

            var quantitiy = 0;
            $('.quantity-right-plus').click(function (e) {

                // Stop acting like a button
                e.preventDefault();
                // Get the field name
                var quantity = parseInt($('#quantity').val());

                // If is not undefined

                $('#quantity').val(quantity + 1);


                // Increment

            });

            $('.quantity-left-minus').click(function (e) {
                // Stop acting like a button
                e.preventDefault();
                // Get the field name
                var quantity = parseInt($('#quantity').val());

                // If is not undefined

                // Increment
                if (quantity > 0) {
                    $('#quantity').val(quantity - 1);
                }
            });

        });
    </script>
{% endblock javascript %}

store/templates/store/products.html
{% extends 'main.html' %}
{% load static %}

{% block title %}  Products || البضائع  {% endblock title %}

{% block body %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url('../../../static/images/bg_2.jpg');"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate mb-5 text-center">
                    <p class="breadcrumbs mb-0"><span class="mr-2"><a href="{% url 'home_page' %}">Home <i
                            class="fa fa-chevron-right"></i></a></span> <span>Products <i
                            class="fa fa-chevron-right"></i></span></p>
                    <h2 class="mb-0 bread">Products</h2>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        {% for product in products %}
                            <div class="col-md-4 d-flex">
                                <div class="product ftco-animate">
                                    <div class="img d-flex align-items-center justify-content-center"
                                         style="background-image: url('{{ product.image.url }}');">
                                        <div class="desc">
                                            <p class="meta-prod d-flex">
                                                <a href="#"
                                                   class="d-flex align-items-center justify-content-center "><span
                                                        class="flaticon-shopping-bag"></span></a>
                                                <a href="#" id="{{ product.pk }}"
                                                   class="d-flex align-items-center justify-content-center sara"><span
                                                        class="flaticon-heart"></span></a>
                                                <a href="#"
                                                   class="d-flex align-items-center justify-content-center"><span
                                                        class="flaticon-visibility"></span></a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="text text-center">
                                        {% if product.status == 1 %}
                                            <span class="sale">Sale</span>
                                        {% elif product.status == 2 %}
                                            <span class="new">New Arrival</span>
                                        {% else %}
                                            <span class="seller">Best Seller</span>
                                        {% endif %}
                                        <span class="category">{{ product.quantity }}</span>
                                        <h2>{{ product.name }}</h2>
                                        <span class="price">${{ product.price }}</span>

                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                    <div class="row mt-5">
                        <div class="col text-center">
                            <div class="block-27">
                                <ul>
                                    <li><a href="#">&lt;</a></li>
                                    <li class="active"><span>1</span></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li><a href="#">&gt;</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="sidebar-box ftco-animate">
                        <div class="categories">
                            <form>
                                {% csrf_token %}
                                <ul class="p-0">
                                    <li>
                                        <div class="form-group">
                                            <label class="label" for="id_price_0">Min Price</label>
                                            <input type="number" class="form-control" name="price_min " id="id_price_0"
                                                   placeholder="Price Min">
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <label class="label" for="id_price_1">Max Price</label>
                                            <input type="number" class="form-control" name="price_max " id="id_price_1"
                                                   placeholder="Price Max">
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <label class="label" for="id_price_0">Product Name</label>
                                            <input type="text" class="form-control" name="name " id="id_name"
                                                   placeholder="Search by Name">
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <label class="label" for="id_status">Status</label>
                                            <select class="form-control" id="id_status" name="status">
                                                <option value="1">Sale</option>
                                                <option value="2">New Arrival</option>
                                                <option value="3">Best Seller</option>
                                            </select>

                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <label class="label" for="id_category">Category</label>
                                            <select class="form-control" id="id_category" name="category">
                                                <option value="1">Skirts</option>
                                                <option value="2">Pantaloon</option>
                                                <option value="3">T-shirt</option>
                                                <option value="4">Sweatshirt</option>
                                                <option value="5">Pullover</option>

                                            </select>

                                        </div>
                                    </li>

                                    <li>
                                        <div class="form-group">
                                            <input type="submit" value="Search" class="btn btn-primary">
                                            <div class="submitting"></div>
                                        </div>
                                    </li>
                                </ul>

                            </form>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <div style="display:flex;" id="myBtn" title="Go to top">
        <a href="#" style="display:flex;" class="btn-cart" aria-haspopup="true" aria-expanded="false">
            <span class="flaticon-shopping-bag"></span>
            <div class="d-flex justify-content-center align-items-center"><small id="cart"></small></div>
        </a>
    </div>

{% endblock body %}

{% block javascript %}
    <script>
        var user_cart = []
        sessionStorage.setItem('user_cart', user_cart);
        $(() => {
            $('a.sara').click(function () {
                var id = $(this).attr('id');
                user_cart.push(id);
                $("#cart").empty();
                $("#cart").append(`${user_cart.length}`);
                sessionStorage.setItem('user_cart', user_cart);
            });
            $("#myBtn").on('click' , event => {
               event.preventDefault();
                  $.ajax({
                    method: 'POST',
                    url: '{% url 'update-session' %}',
                    data: {
                        'items[]': user_cart,
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function (data) {
                      window.location.href = '{% url 'carts' %}'
                    },
                    error: function (error) {
                        alert(error.responseText)
                    }
                });

            });


        });
    </script>

{% endblock javascript %}